import { useSummarizeNoteMutation } from "../../apis/notes-api";
import { Sparkles } from "lucide-react";

interface SummaryTabProps {
  noteId: number;
  summary: string | null;
  content: string;
}

const SummaryTab = ({ noteId, summary, content }: SummaryTabProps) => {
  const [summarizeNote, { isLoading: isSummarizing }] =
    useSummarizeNoteMutation();

  const handleSummarize = async () => {
    try {
      await summarizeNote(noteId);
    } catch (error) {
      console.error("Failed to generate summary:", error);
    }
  };

  if (summary) {
    return (
      <div className="p-6 bg-gradient-to-br from-yellow-50 to-amber-50 border border-yellow-200 rounded-xl">
        <div className="flex items-start gap-3 mb-4">
          <div className="p-2 bg-yellow-100 rounded-lg">
            <Sparkles className="h-5 w-5 text-yellow-600" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-yellow-900">AI Summary</h3>
            <p className="text-sm text-yellow-600">Generated by AI</p>
          </div>
        </div>
        <p className="text-gray-700 leading-relaxed">{summary}</p>
      </div>
    );
  }

  return (
    <div className="p-12 text-center">
      <div className="max-w-md mx-auto">
        <div className="p-4 bg-yellow-100 rounded-full w-16 h-16 mx-auto mb-4 flex items-center justify-center">
          <Sparkles className="h-8 w-8 text-yellow-600" />
        </div>
        <h3 className="text-lg font-semibold text-gray-900 mb-2">
          Generate AI Summary
        </h3>
        <p className="text-gray-500 mb-6">
          Get a concise summary of your note powered by AI
        </p>
        <button
          onClick={handleSummarize}
          disabled={isSummarizing || !content}
          className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-lg hover:from-purple-700 hover:to-indigo-700 disabled:from-gray-300 disabled:to-gray-400 disabled:cursor-not-allowed transition-all shadow-md hover:shadow-lg"
        >
          <Sparkles className={`h-5 w-5 ${isSummarizing ? "animate-pulse" : ""}`} />
          {isSummarizing ? "Generating..." : "Generate Summary"}
        </button>
      </div>
    </div>
  );
};

export default SummaryTab;
